language/doublecmd.nl.po
Hi!
Modification suggested by a friend.
It is also a kind of pull request exercise in GitHub for me.
=> FIX: Bad format messages in Dutch language file.

language/doublecmd.fr.po, language/doublecmd.nl.po
Hi!
French language file was a little way behind. It would now be up to date.
Thanks you!
=> Completion of French language file.

language/doublecmd.nl.po
Thanks to Martijn Online for his contribution.
=> UPD: Dutch language file improvement

src/feditor.pas
Option "Selected text only" in Editor enabled if text is highlighted
=> ADD: Feature [0002653] "Selected text only" enable if text highlighted

language/doublecmd.ko.po
fixed bad format 
#: fsyncdirsdlg.rslefttorightcopy
#: fsyncdirsdlg.rsrighttoleftcopy
=> UPD: Korean translation

language/doublecmd.fr.po
Several improvements in French translation (use verbs at infinitive, add missing translations...).
=> UPD: French translation

src/uluapas.pas
`SysUtils.GetAbsolutePath()` and `SysUtils.GetRelativePath()`.
=> ADD: Lua - GetAbsolutePath, GetRelativePath functions

src/platform/win/uwin32widgetsetdark.pas
Make the selected tab more easily discernable
=> UPD: Dark mode - selected tab background color

src/platform/win/uwin32widgetsetdark.pas
=> UPD: Dark mode - graytext color

src/platform/win/uwin32widgetsetdark.pas
improve consistency and visibility
=> UPD: Dark mode - border color for checkbox & radio button

src/frames/fquicksearch.pas
Did not occurred any problems after using for half a day, so maybe this is a correct way to fix #274
=> FIX: Reset filter field everytime when gaining focus (fixes #274)

README.md
Thank you for the nice project!
=> Improve readability and formatting

src/fileviews/ufileviewwithmainctrl.pas, src/fmain.pas
switch panel and tab when mouse down on MacOS, more like on windows(and TC)
I have test it on MacOS, please check it.
=> UPD: Cocoa: switch panel and tab more like on windows(when mouse down)

src/platform/upixmapmanager.pas
FIX: get the app icon filename by native method, support Binary format of Info.plist, replace the original HACK code
=> FIX: get the app icon filename by native method

src/platform/unix/darwin/umydarwin.pas, src/platform/unix/ushellcontextmenu.pas, src/platform/uosforms.pas
ADD: MacOS: add System Services Sub Menu to PopupMenu(Consistent with the Services Menu in the Main Menu)
=> ADD: MacOS: add System Services Sub Menu to PopupMenu

src/platform/unix/darwin/umydarwin.pas, src/platform/unix/ushellcontextmenu.pas, src/platform/uosforms.pas, src/ulng.pas
add `Services` Popup Menu item i18n supports
=> UPD: MacOS: add Service PopUp Menu Item i18n supports

src/platform/uClipboard.pas, src/platform/unix/darwin/umydarwin.pas
UPD: Refactor: remove Duplicate Code in uClipboard
=> UPD: Refactor: remove Duplicate Code in uClipboard

src/fcopymovedlg.lfm, src/fcopymovedlg.pas
fix #340 and #341 
tested on MacOs and Windows
=> FIX: COCOA: controls position error in CopyMoveDlg

src/fileviews/ufileviewwithmainctrl.pas
1. when using F2-Rename in MacOS, RETURN KEY is incorrectly handled in IME input state. the intermediate typing text is returned as the result, then returns directly and incorrectly changes the filename.
2. the correct way is to receive IME text, and still in the Rename EditButton, just like other apps on MacOS and DC on Windows.
3. tested on MacOS and Windows.
=> FIX: COCOA: F2-Rename EditButton: VK_RETURN handler in IME state

src/platform/udragdropex.pas
UPD: hold ALT key while dragdropping, popup ask menu (Copy/Move/Create Link/...), especially useful on Macs (due to lack of right mouse button)
=> UPD: hold ALT key while dragdropping, popup ask menu

src/fmkdir.lfm, src/fmkdir.pas
UPD: F7-mkdir: improve the layout, add space between controls.
and avoid label example overlay buttons when "Extended syntax" checked.
=> UPD: F7-mkdir: improve the layout (label example overlay buttons occasionally)

components/KASToolBar/kaspathedit.pas, src/fileviews/ufileviewheader.pas
1. when using PathEdit in MacOS, RETURN KEY and ESCAPE KEY are incorrectly handled in IME input state.
2. the intermediate typing text is returned as the result when RETURN KEY pressed, then returns directly and incorrectly changes the path. the correct way is to receive IME text, and still in the PathEdit, just like other apps on MacOS and DC on Windows.
3. PathEdit will be completely canceled when ESCAPE KEY pressed. the correct way is to ignore IME intermediate typing text only, and still in the PathEdit, just like other apps on MacOS and DC on Windows.
4. tested on MacOS and Windows.
=> FIX: COCOA: kaspathedit in IME state

src/fileviews/ufileviewwithmainctrl.pas
1. refactor TEditButtonEx and TFileViewWithMainCtrl, the code related to IME input state
2. the code is simpler, more reasonable, and more readable (refer to KASPathEdit)
3. tested on MacOS and Windows
=> UPD: Refactor TEditButtonEx and TFileViewWithMainCtrl

components/KASToolBar/kaspathedit.pas
more suitable ClientHeight of autocomplete window: one file, more than 10 files
=> UDP: COCOA: more suitable ClientHeight of autocomplete window

components/KASToolBar/kaspathedit.pas
more proper showing and hiding of AutoComplete ListBox in KASPathEdit:
1. when the AutoComplete ListBox is showing, pressing VK_ESCAPE only closes the AutoComplete ListBox, which is consistent with the Windows version
2. when the AutoComplete ListBox is showing, pressing VK_RETURN only closes the AutoComplete ListBox, which is more in line with the user's operating habits and avoids misoperation.
3. when there are no matching files (ListBox is empty), close the AutoComplete Window
4. only the Cocoa version is optimized, other versions remain unchanged
5. tested on MacOS 12 and Windows 11
=> UPD: COCOA: more proper showing and hiding of AutoComplete ListBox in KASPathEdit

src/uwlxmodule.pas
add implement ResizeWindow in TWlxModule on MacOS
=> ADD: DARWIN COCOA: implement ResizeWindow in TWlxModule

plugins/wlx/MacPreview/src/MacPreview.lpi, plugins/wlx/MacPreview/src/MacPreview.lpr
add a WlxPlugin MacPreview:
1. implemented using MacOS Native QuickLook Preview
2. handle all files except those without extension
3. tested on MacOS 12
=> ADD: DARWIN: add a WlxPlugin MacPreview

fpmake.pp, install/darwin/install.sh, plugins/build.sh, src/platform/udefaultplugins.pas
1. build MacPreview.wlx  with plugins/build.sh
2. install MacPreview.wlx with install/create_packages.mac
=> UPD: DARWIN: enable MacPreview wlx-plugin

plugins/wlx/MacPreview/src/MacPreview.lpr
workaround for the bug of MacOS Quick Look:
when previewing different types of files continuously, occasionally exceptions occur.
such as previewing a large .pas file immediately after previewing a pdf file.
empty the original preview file first can solve such problems.
=> FIX: DARWIN: MacPreview: workaournd for the bug of MacOS Quick Look

plugins/wlx/MacPreview/src/MacPreview.lpr
MacPreview: change extension comparison to case insensitive, and some small improvements to the code
=> UPD: MacPreview: change extension comparison to case insensitive

src/fileviews/ucolumnsfileview.pas
A bit of obsessive mimicking of Total Commander. The discussion is in the end of #207 
Please consider.
=> A cosmetic change for 09f989d4. Show [brackets] around directories names in the status bar if nothing is selected.

README.md
=> Added clarifications

components/KASToolBar/kaspathedit.pas, src/fFindDlg.pas, src/feditor.pas, src/fileviews/ufileviewwithmainctrl.pas, src/platform/unix/darwin/umydarwin.pas, src/ufileviewnotebook.pas
Comments: Add six notes to optimize codes in the future.
=> Comments: Add six notes to optimize codes in the future

src/platform/ufilesystemwatcher.pas, src/platform/unix/darwin/udarwinfswatch.pas
ADD: FileSystemWatch: File-Level update supported on MacOS.
include fswFileCreated, fswFileDeleted, fswFileChanged, fswSelfDeleted.
`Auto Refresh` significantly improved on MacOS.
=> ADD: FileSystemWatch: File-Level update supported on MacOS

src/platform/ufilesystemwatcher.pas, src/platform/unix/darwin/udarwinfswatch.pas
fine-tuning File-Level update on MacOS.
=> UPD: FileSystemWatch: fine-tuning File-Level update on MacOS

src/platform/ufilesystemwatcher.pas
`Auto Refresh` options supported on MacOS
=> ADD: Auto Refresh: options supported on MacOS

src/ufile.pas
TFile.IsSysFile: 'Icon'#$0D is system/hidden file on MacOS
=> UPD: TFile.IsSysFile: 'Icon'#$0D is system/hidden file on MacOS

src/platform/udcversion.pas
* ADD GetStringsFromEqFile for parsing A=B
* FIX reorder /etc/issue parsing
- Make `src/platform/udcversion.pas` parse `/etc/os-release` which gets setup by almost all systemd based linux distros.
- reorder "last resort" parsing of `/etc/issue` since it may contain anything but system information on most systems
=> ADD: Support parsing of /etc/os-release

src/fileviews/ufileview.pas, src/platform/ufilesystemwatcher.pas, src/platform/unix/darwin/udarwinfswatch.pas
in FlatView Mode, files in subdir are listed together.
auto refresh of subdir files was not supported before.
now it's supported on MacOS.
=> ADD: AutoRefresh: subdir in FlatView Mode supported on MacOS

src/fmain.lfm, src/fmain.pas, src/udcutils.pas
It's limited by 1/3 of the panel width (simillar the main window width) and after minimize long full path and set width to fit the shorten path.
=> UPD: Better looking for command line

src/platform/ufilesystemwatcher.pas, src/platform/unix/darwin/udarwinfswatch.pas
Renamed Event supported in fswatch on MacOS.
it will reload() all before, when file renamed on MacOS.
=> UPD: DARWIN: Renamed Event supported in fswatch on MacOS

src/platform/unix/darwin/udarwinfswatch.pas
compatible with previous versions of MacOS 10.13
=> UPD: FileSystemWatch: compatible with previous versions of MacOS 10.13

src/platform/ufilesystemwatcher.pas
check Main Thread before Synchronize() when DoWatcherEvent in uFileSystemWatcher.
to avoid possible deadlocks when exiting DC.
because if Main Thread terminated, calling Synchronize() will never return.
tested on MacOS 12, Windows 11, and Linux.
=> FIX: check Main Thread before Synchronize() when DoWatcherEvent in uFileSystemWatcher

src/platform/unix/darwin/udarwinfswatch.pas
reduce deepCopy in fswatch on MacOS.
=> UPD: DARWIN: reduce deepCopy in fswatch on MacOS

.gitignore
add .DS_Store to .gitignore, useful on MacOS.
=> UPD: add .DS_Store to .gitignore

src/platform/unix/darwin/udarwinfswatch.pas
UPD: fine-tuning syntax in udarwinfswatch
=> UPD: fine-tuning syntax in udarwinfswatch

src/platform/unix/darwin/ucocoawidgetsetfix.pas
exception raised when closing the Form with the ComboBox in IME input state.
see also: https://gitlab.com/freepascal.org/lazarus/lazarus/-/merge_requests/117
=> FIX: COCOA: Exception in ComboBox

src/platform/unix/darwin/udarwinfswatch.pas
faster response to file changed events on MacOS.
base on #867 (smarter visual blinking in TFileView.UpdateFile)
=> UPD: faster response to file changed events on MacOS

src/platform/win/uTotalCommander.pas, src/uhotdir.pas
Fixed Directory Hotlist import from Total Commander inifile.
Reading [DirMenu] entries now respects 'RedirectSection' key.
=> Add 'RedirectSection' key support for TC ini

language/doublecmd.zh_CN.po
missing zh_CN translations added
=> ADD: LANG: zh_CN: missing translations added

language/doublecmd.zh_CN.po
fix translation issues in zh_CN
=> FIX: LANG: zh_CN: translations

language/doublecmd.zh_TW.po
a large number of commonly used translations of zh_TW added and improved.
=> UPD: LANG: zh_TW: a large number of commonly used translations added and improved

language/doublecmd.zh_CN.po
=> UPD: LANG: zh_CN: translations

src/fileviews/ucolumnsfileview.pas
1. Adding padding for right alignment columns.
2. Adding padding for the last row in file list (grid).
Before: https://skr.sh/sJ1gTQUPLLl
After: https://skr.sh/sJ16s6rVxyG
Sorry for colours. It's the best for testing purpose.
=> UPD: adding padding for file list in FileView to the bottom and to the right for column right text alignment

components/doublecmd/dcosutils.pas
=> ADD: copy file with CreationTime on MacOS

src/fmain.pas, src/umaincommands.pas
Subj and I don't understand for what exists DoSortByFunctions. I think for the future so what's why I decided to leave this function,
But all callings with one element array and this cycle doesn't make sense:
```
// Check if there is already sorting by one of the functions.
// If it is then reverse direction of sorting.
for i := 0 to Length(FileFunctions) - 1 do
begin
SortDirection := GetSortDirection(CurrentSorting, FileFunctions[i]);
if SortDirection <> sdNone then
begin
SortDirection := ReverseSortDirection(SortDirection);
Break;
end;
end; 
```
So ... to live or to die this function and if to die I can merge DoSortByFunctions with my new one DoSortOneFunction.
=> Fix: Sorting after first install and small refactoring

components/doublecmd/dcosutils.pas, components/doublecmd/dcunix.pas, src/ffileproperties.lfm, src/ffileproperties.pas, src/filesources/filesystem/ufilesystemfilesource.pas, src/platform/ufindex.pas
dialog `Show File Properties`: `Creation time` shown on MacOS
=> UPD: ShowFileProperties: show Creation time on MacOS

src/filesources/filesystem/ufilesystemfilesource.pas
CreationTime Column Supported on MacOS.
=> ADD: CreationTime Column Supported on MacOS

src/platform/unix/darwin/udarwinfswatch.pas
FIX #954: AutoRefresh: symlink issue on MacOS
=> FIX #954: AutoRefresh: symlink issue on MacOS

src/platform/unix/darwin/udarwinfswatch.pas
fix sync issue in fswatch on MacOS.
see also: #967
=> FIX: fswatch sync issue on MacOS

components/KASToolBar/kaspathedit.pas
[LCL: COCOA: IME fully supported on MacOS #40008](https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/40008) was merged.
so the workaround for IME in `pathedit` can be removed.
PS. on MacOS, in the internal editor of DC,  IME fully supported from the moment, such as Chinese/Japanese/Korean.
=> UPD: workaround for IME in pathedit are removed by the update of Lazarus Lcl (issue 40008)

src/platform/unix/darwin/ucocoawidgetsetfix.pas
the workaround for IME and Release in TCocoaWSCustomComboBoxEx can be removed.
=> UPD: workaround for IME in TCocoaWSCustomComboBoxEx are removed by the update of Lazarus Lcl (issue 40008)

src/fileviews/ufileviewwithmainctrl.pas, src/fmain.pas, src/platform/unix/darwin/umydarwin.pas
Cocoa/Cursor related code removed by new Lcl/Cocoa version.
and #1009 should be fixed.
=> Fix #1009: Cocoa: Cursor related code removed by new Lcl/Cocoa version

language/doublecmd.hu.po
Hungarian language file updated
(I am the original translator, but since my mother has passed away [2016] I was lost....)
=> Hungarian language file updated

src/uspecialdir.pas
Cosmetic rearrangement of the different special folder names for better understanding of the source code.
=> Reorder special folders names

language/doublecmd.fr.po
Hi
I propose the following additions/corrections to the French translation file.
=> Update french translation

language/doublecmd.fr.po
Hi,
Some corrections on the French translation proposed to merge into the active branch 1.1x
Thanks
=> Corrections on the French translation

src/uluapas.pas
DC.ExpandVar, DC.GetPluginField, DC.GoToFile, DC.ExpandEnv;
SysUtils.FileSetTime, SysUtils.GetFileProperty, SysUtils.RemoveDirectory.
=> Some additional functions for Lua

default/multiarc.ini, src/umultiarc.pas
=> ADD: FallBackArchivers

src/filesources/multiarchive/umultiarchiveutil.pas, src/umultiarc.pas
stuff from far, but its quite usefull for multiline parsing eg -slt from 7z
=> ADD: MultiArc - IgnoreString support

src/ufilesorting.pas
=> CHG: More correct sorting of the "Path" and "Link to" fields.

highlighters/Kotlin.hgl, highlighters/highlighters.json
Пока добавляю только тёмную тему (Dark)
Светлая генерируется сама из базовых цветов, пока не понял как её сделать в hgl
=> ADD: Kotlin syntax highlight

highlighters/QML.hgl, highlighters/highlighters.json
Basic QML + SFOS + Aurora OS
Light & Dark
=> ADD: QML syntax highlighter
