doublecmd/doublecmd

- language/doublecmd.de.po
German translation of 
Menu -> Files -> Create Shortcut
which actually is this
Menü -> Dateien -> Tastaturkürzel erstellen ...
is wrong and should be replaced by:
Menü -> Dateien -> Verknüpfung erstellen ...
Changed text in line 10769
> Fix German translation of Menu-Text (Win-Version)

- src/fsyncdirsdlg.pas
Long file names in "Synchronize directories" window overlap "Date" columns.
I replaced "TDrawGrid.Canvas.TextOut()" with "TDrawGrid.Canvas.TextRect()" function. The rectangle overlaps previous text in column.
> FIX: Bug [0001128] Long file names in "Synchronize directories"

- plugins/wdx/audioinfo/audioinfo.lng
- plugins/wdx/audioinfo/src/AudioInfo.lpr
The fields 'Duration' and 'Duration (H/M/S)' were renamed.
UPD: audioinfo.lng.
> CHG: AudioInfo: 'Duration' returns duration as a number in seconds.

- install/create_packages.bat
- install/windows/doublecmd.iss
Currently, the EXE file does not set the `DisplayVersion` or `Publisher` entries in control panel.
The MSI files do set these values. 
This change should update the EXE files that are built to set these additional parameters
> Feat: Add Version Pubilsher to ARP Entries

- src/fFindDlg.pas
- src/ufindthread.pas
- src/uregexpr.pas
- src/uregexpru.pas
Added the `ReplaceAll` method to the `TRegExprU` class.  
FindThread uses`TRegExprEx` instead of `TRegExpr`.  
In FindDlg the `cbTextRegExp` checkbox is enabled if the file encoding is UTF8 (or Default).  
"Replace all" is implemented only for PCRE2, so functionality is enabled only if the libpcre2 library is available.
> Find and replace using RegEx in UTF8 encoded files

- src/fFindDlg.pas
- src/uregexpru.pas
* FIX: Added regexpr validation for UTF8 encoded files in `TfrmFindDlg.InvalidRegExpr` method
* ADD: Added `ExecRegExpr` function to `uregexpru` unit
* FIX: Trimming string length after calling `pcre2_get_error_message`
Related to 9b479b80
> RegExpr validation for UTF8 encoded files in TfrmFindDlg.InvalidRegExpr method

- components/doublecmd/dcdatetimeutils.pas
- plugins/wcx/unrar/src/unrarfunc.pas
- src/dmcommondata.pas
- src/filesources/filesystem/ufilesystemutil.pas
- src/filesources/wcxarchive/uwcxarchivecopyoutoperation.pas
- src/filesources/wfxplugin/uwfxpluginutil.pas
- src/fmain.pas
- src/ufilefunctions.pas
The source file has been modified to allow doublecmd to be compiled with the current (trunk / main) version of FPC.  
At the same time, the project can also be compiled using FPC 3.2
> FIX: FPC 3.3 compatibility

- install/linux/doublecmd.desktop
this 'GenericName' is shown in KDE's Application Launcher
without this key 'Comment' is used instead, and it looks bad, because comment is long
key/value pair was taken from KDE's Krusader
> ADD: GenericName key to .desktop file

- src/platform/win/uwin32widgetsetdark.pas
Make menu separator lines visible in dark mode. The previous color was too dark to be seen.
> UPD: Dark mode - menu separator lines

- src/fileviews/ufileviewwithmainctrl.pas
FIX [#419](https://github.com/doublecmd/doublecmd/issues/419): Cocoa: Exception raised after directory opened in new Tab with double click (Cannot focus a disabled or invisible window)
> FIX #419: Cocoa: Exception raised after directory opened in new Tab with double click (Cannot focus a disabled or invisible window)

- src/ufileviewnotebook.pas
FIX the bug reported in DC Forum: [Mac - move tabs](https://doublecmd.h1n.ru/viewtopic.php?p=32839#p32839)
> FIX: Cocoa: according page not actived after tab moved(dragdrop)

- src/ufileviewnotebook.pas
on Cocoa, FileViewNoteBook will fall into chaos, caused by popup menu after DblClick(after MouseDown but before MouseUp) on tabs.
DblClick event have to be triggered after MouseUp on Cocoa.
> FIX: Cocoa: FileViewNotebook will fall into chaos, caused by popup menu after DblClick on tabs

- src/fmain.pas
FIX: in MacOS, incorrectly setting the AllowDropFiles property, preventing dragdrop files from external apps
> FIX: DARWIN: incorrectly setting the AllowDropFiles property, preventing dragdrop files from external apps

- src/filesources/filesystem/ufilesystemdeleteoperation.pas
- src/fsyncdirsdlg.pas
patch for [https://github.com/doublecmd/doublecmd/issues/481](https://github.com/doublecmd/doublecmd/issues/481) 
Cocoa: hard to see in "Synchronize directories" (transparent background by "clDefault" color)
> FIX & UPD: Issues related to "Synchronize directories"

- src/platform/unix/ushellcontextmenu.pas
- src/platform/upixmapmanager.pas
FIX: DARWIN: load the icon file content by native method, support all MacOS ICNS formats (bitmap/png/jpeg), and avoid limited image formats support of Lazarus.
tested on MacOS and Windows.
> FIX: DARWIN: load the icon file content by native method

- install/create_packages.mac
trying to launch nightly aarch64 build faced this error:
launch from the terminal was successful, and everything looks fine, the app is at least usable.
just doing ad-hoc signing before dropping the application into the Applications directory fixes this issue. so, let's do a signing in the build script (this still will be considered as an "untrusted" application in any case).
very strange that everything is fine on Intel-based MacBook running the same macOS version. very likely macOS on ARM-based Mac is much more "phone-like"...
> FIX: use ad-hoc signing, fixes "Double Commander is damaged" on ARM-based Macs

- src/platform/udrivewatcher.pas
- src/platform/unix/darwin/umydarwin.pas
FIX: DARWIN: aarch64: get mounted driver infomation error.
cause by TStatFS bug of FPC RTL ([issue #39873](https://gitlab.com/freepascal.org/fpc/source/-/issues/39873))
> FIX: DARWIN: aarch64: Mounted Driver <no label>

- src/fmkdir.lfm
- src/fmkdir.pas
1. In Lazarus 2.2, it is no longer necessary to handle the Enter key in TForm.OnKeyPress
2. After removing the OnKeyPress code, the IME state can be handled correctly
> FIX: F7-mkdir: VK_ESCAPE VK_RETURN in IME state

- src/fileviews/ufileviewwithmainctrl.pas
1. when using F2-Rename in MacOS, ESCAPE KEY is incorrectly handled in IME input state, EditBuuton will be completely canceled.
2. the correct way is to ignore IME intermediate typing text only, and still in the Rename EditButton, just like other apps on MacOS and DC on Windows.
3. tested on MacOS and Windows.
> FIX: COCOA: F2-Rename EditButton: VK_ESCAPE handler in IME state

- install/create_packages.mac
the earliest version of MacOS that supports aarch64 (M1) is 11.0
set MACOSX_DEPLOYMENT_TARGET to 11.0 when create aarch64 package.
and keep 10.5 when create x86_64 package.
> FIX: DARWIN: set MACOSX_DEPLOYMENT_TARGET to 11.0 on aarch64 CPU_TARGET

- src/upathlabel.pas
in some WidgetSets such as Cocoa, the width of the text is related to the relative position of the characters in the string.
for examples:
1. Canvas.TextWidth( '/1测试1' ); // is 46
2. Canvas.TextWidth( '/测1试1' ); // is 49
in 2nd case, HighLightPos calculation error in PathLabel.highlight.
this commit will fix it.
tested on MacOS and Windows.
> FIX: PathLabel: HighLightPos calculation error, when PathDelim is next to Chinese

- src/upathlabel.pas
1. in PathLabel, the current version only highlights the path selected in the MouseOver Event.
2. when the mouse first enters the PathLabel, it may only trigger the MouseEnter Event, resulting in missing highlighting.
3. fix the problem by adding highlight related codes in MouseEnter Event.
4. tested on MacOS and Windows.
> UPD: PathLabel: add highlight calling in MouseEnter

- components/KASToolBar/kaspathedit.pas
fix mouse event lost in AutoComplete List in KASPathEdit:
1. autocomplete list doesn't respond properly to mouse events on MacOS
2. it's because in `TCCoaWSHintWindow` the HintWindow is set to not respond to mouse events by `win.setIgnoresMouseEvents(True)`
3. fixed the problem by `setIgnoresMouseEvents(false)`
4. it's more like on Windows now
5. tested on MacOS 12 and Windows 11
> FIX: COCOA: mouse event lost in AutoComplete List in KASPathEdit

- src/uquickviewpanel.pas
fix the problem of displaying wrong hint text in QuickViewPanel
1. disable hint text in QuickView
2. tested on MacOS 12 and Windows 11
> FIX: fix the problem of displaying wrong hint text in QuickViewPanel

- components/KASToolBar/kaspathedit.pas
the last part of the text in the TEdit is automatically selected, when selecting from AutoComplete ListBox in KASPathEdit, more like on Windows.
tested on MacOS 12 and Window 11.
> UPD: the last part of the text in the TEdit is automatically selected, when selecting from AutoComplete ListBox in KASPathEdit

- src/fFindDlg.lfm
FIX: FindDlg: the buttons are not shown because the height of the FindDlg Form is insufficient after upgrading to LCL2.2.4
1. after many tests, it was found that the problem was caused by the upgrade of this LCL commit (at 2022.5.17): https://gitlab.com/freepascal.org/lazarus/lazarus/-/commit/64bc8e992e3be1acc1104d406a4f0633516490fa
2. once we have found the cause, simply set the FindDlg's `AutoSize:=true` to fix the issue
3. works well in every situation, including resizing the FindDlg Form
3. tested on MacOS 12 and Windows 11
> FIX: FindDlg: the buttons are not shown

- src/fileviews/ufileviewheader.pas
FIX: garbled when editing in FileViewHeader:
1. this problem only occurs on MacOS and dark mode
2. in dark mode, the TEdit with border becomes transparent, and the PathEdit fails to cover the PathLabel
3. set PathEdit to opaque by BorderStyle:=bsNone
4. tested on MacOS 12 and Windows 11
> FIX: COCOA: garbled when editing in FileViewHeader

- src/fFindDlg.pas
improve some inconvenience problems:
1. remove useless code
2. after searching, if there is something found in the Result ListBox, focus on the Result ListBox and the GotoPath Button
3. after FindDlg is shown, set AutoSize:=false to prevent Result ListBox from changing the height of FindDlg
4. no matter how the user enters the tsStandard TabSheet, focus on the btnStart Button and cmbFindFileMask ComboBox
> UPD: FindDlg: improve some inconvenience problems

- src/fviewer.pas
Not exiting PluginMode when receiving empty string in TfrmViewer.LoadFile().
will cause multiple Plugins content to be overlaped.
```pascal
procedure TfrmViewer.LoadFile(const aFileName: String);
......
if dwFileAttributes = faInvalidAttributes then
begin
ActivatePanel(pnlFolder);
ExitPluginMode;  // missed before
----------------
memFolder.Font.Color:= clRed;
memFolder.Lines.Text:= rsMsgErrNoFiles;
Exit;
end;
procedure TQuickViewPanel.FileViewChangeActiveFile(Sender: TFileView; const aFile: TFile);
......
except
on E: EAbort do
begin
FViewer.Hide;
FFirstFile:= True;
Caption:= E.Message;
FViewer.LoadFile(EmptyStr);
---------------------------
end;
end;
```
> FIX: QuickView: Not exiting PluginMode when receiving empty string in TfrmViewer.LoadFile()

- src/platform/udrivewatcher.pas
ADD: DARWIN: new FileSystemType 'lifs' supported in MacOS 13
FIX:#651 External USB flash drive not shown in drives list
> ADD: DARWIN: new FileSystemType 'lifs' supported in MacOS 13 (FIX:#651)

- src/platform/unix/umyunix.pas
unmount driver by TDrive.path to compatible with MacOS 13 (TDrive.DeviceId changed)
> FIX: DARWIN: unmount driver compatible with MacOS 13

- src/ufileviewnotebook.pas
FIX: TFileViewNotebook.DestroyAllPages: algorithm of clear tabs
when switching Favorites, a large number of Tabs that will be removed are activated unnecessarily.
this is because in `TFileViewNotebook.DestroyAllPages()` call `Tabs.Clear()`. the Clear() algorithm will cause the next Tab to be activated time by time after removing the currently active Tab. even FCanChangePageIndex:=False doesn't work.
In some cases, it will cause LCL control exception. for example, in `Thumbnails View` mode, in the Destroy process, because the Tab is reactivated, MakeFileSourceFileList() is restarted, and then TFunctionThread is restarted to update data in the background. at this time, the LCL control has been destroyed, thus exception thrown.
it exists at least in Cocoa, because NSTabView cannot be in the …
> FIX: TFileViewNotebook.DestroyAllPages: algorithm of tabs.clear()

- src/fileviews/uorderedfileview.pas
there is a problem when `F2 Rename` in the `Quick View` state, the Viewer is set to "..".
it's because in TOrderedFileView.SetActiveFileNow(), TOrderedFileView.OnChangeActiveFille() is missed, when F2 Rename and the Index value of the file is not changed.
> FIX: FileView: missing call to TOrderedFileView.OnChangeActiveFille()

- src/fileviews/ucolumnsfileview.pas
Useful at times. Without it, the only way I found to see where symlink is pointing is to go open its properties.
> ADD: show link targets in status bar

- src/fileviews/ufileview.pas
- src/fileviews/ufileviewwithmainctrl.pas
- src/fmain.pas
- src/platform/unix/darwin/umydarwin.pas
on MacOS, background color not updated in FileView after theme changed.
fixed by monitoring Theme is changed and updating MainControl.Color.
tested on MacOS 12 and Windows 11.
> FIX: MacOS: color not updated in FileView after theme changed

- src/fFindDlg.lfm
- src/fFindDlg.pas
FIX #621 : FindDlg: buttons not shown:
1. the Caption of the buttons in `pnlButtons` are too long to accurately calculate the height of `pnlButtons`
2. the height of TabSheets affected by pnlButtons, and are increased by 30 points incorrectly
3. therefore the buttons in TabSheets align to bottom are not visible
4. fix the issue by canceling `autosize` of pnlButtons
tested on MacOS 12 and Windows 11
> FIX #621: FindDlg: buttons not shown

- src/fmain.pas
FIX #699 #728: Cursor not reset in new Active Window on MacOS 13.
on MacOS 13, it seems that independent windows have their own exclusive Cursor settings.
the simple understanding is that each independent window has its own Screen.Cursor.
> FIX #699: DARWIN: Cursor not reset in new Active Window on MacOS 13

- src/fmain.pas
FIX #731: DARWIN: Cursor not reset in Reactive Application on MacOS 13
> FIX #731: DARWIN: Cursor not reset in Reactive Application on MacOS 13

- src/fmain.pas
FIX #733 again: DARWIN: Cursor not reset in Reactive Application on MacOS 13
> FIX: DARWIN: Cursor not reset in Reactive Application on MacOS 13 again (#733)

- src/fmain.pas
- src/uquickviewpanel.pas
in the QuickView state, switching Favorites Tabs causes an exception.
it's because the FileView has been released before `TfrmMain.nbPageChanged()`.
this problem exists in all OS/Interface.
```
| DC v1.1.0 alpha Rev. 10529 -- aarch64-Darwin-cocoa
| Mac OS X 12.6.2 | PID 2598
Unhandled exception: EAccessViolation: Access violation
Stack trace:
$0000000101530174 line 1384, column 6 of fileviews/ufileviewwithmainctrl.pas in /Applications/（10529）Double Commander.app/Contents/MacOS/doublecmd
$0000000100EC1BF8 in /Applications/（10529）Double Commander.app/Contents/MacOS/doublecmd
$0000000100F43A54 in /Applications/（10529）Double Commander.app/Contents/MacOS/doublecmd
$00000001015F12E4 line 86, column 3 of uquickviewpanel.pas in /Applications/（10529）Double Commander.app/Contents/MacOS/doublecmd …
```
> FIX: the order of closing FileView and closing QuickView

- src/doublecmd.lpr
- src/fmain.pas
on MacOS, Window state was not properly restored on startup.
it's because that setting WindowState in `DoFirstShow()` is not working properly on Cocoa.
> FIX: COCOA: Window state was not properly restored on startup

- src/platform/unix/darwin/umydarwin.pas
- src/uglobs.pas
two issues about Termianl fixed:
1. fixed Terminal.app default location by `NSWorkspace.sharedWorkspace.fullPathForApplication` on MacOS
2. fixed the bug about RunTermParams when `JustRunTerminal` and `RunTerminal` are both missing. 
PS. #377 should be closed.
> FIX: issues about Terminal

- src/uquickviewpanel.pas
improve directories display in QuickView:
1. refactoring `TQuickViewPanel.FileViewChangeActiveFile` to use normal flow control statements, use exceptions only when error occurs. while keeping the original function unchanged with FileSystem, Ftp, and Search Results.
2. Improvement: '..' and root can be displayed correctly in FileSystem
3. Improvement: directories can be displayed correctly in Search Results
4. Improvement: avoid wrongly displaying directory link symbols in Ftp
tests performed：
1. tested with FileSystem, Ftp, and Search Results
2. tested with normal directories, '..', and root
3. tested on MacOS 12 and Windows 11
> UPD: Improve directories display in QuickView

- src/ufileviewnotebook.pas
FIX: TFileViewNotebook.DestroyAllPages: 
1. there is a bug in `TFileViewNotebook.DestroyAllPages`, the ViewPage is not properly destroyed.
2. `Tabs.Delete()` should be called when removing page, not `inherited RemovePage()`.
3. `Tabs.Delete()` consistent with `TNBPages.Clear`, it will call `TNBPages.Delete` at the end. the ViewPage will be properly destroyed.
4. `inherited RemovePage()` will call `TNBPages.DeletePage` at the end. it just remove the ViewPage from the list, the ViewPage will not be destroyed.
```pascal
procedure TNBPages.Clear;
var
i: Integer;
begin
// remove the pages in reverse order but skip the Active Page,
// and remove the Active Page at the end,
// to avoid activating other Pages.
for i:=FNoteBook.PageCount-1 downto 0 do
if i<>FNoteBook.PageIndex then Delete(i);
if …
```
> FIX: TFileViewNotebook.DestroyAllPages: remove page by Tabs.Delete()

- src/doublecmd.lpi
- src/platform/ufilesystemwatcher.pas
- src/platform/unix/darwin/udarwinfswatch.pas
`Auto Refresh` on MacOS does not work well.
ie. the issue like #755, or overwrite existing file, or creating new large file.
it's because `file attributes monitoring` is missing with `kqueue/kevent`.
in this PR, `fsevents` used instead of `kqueue/kevent` on MacOS.
1. multiple directories can be monitored at the same time. DC generally monitors more than two directories (possibly much more than two), just one TDarwinFSWatcher needed.
2. subdirectories monitor supported. currently in DC, only one level needed.
3. file attributes monitoring is supported, and monitoring of adding files, renaming files, deleting files is also supported. for comparison, file attributes monitoring is missing with kqueue/kevent.
4. CFRunLoop is used in TDarwinFSWatcher. because in DC a separate thread has been …
> ADD: FileSystemWatcher: use fsevents instead of kqueue/kevent on MacOS

- src/platform/ukeyboard.pas
11 keys added to uKeyboard for Windows and MacOS.
this corresponds to the keys that can set ShortCuts on Linux.
tested on MacOS 12 and Windows 11.
> UPD:  ShortCuts: 11 keys added to uKeyboard for Windows and MacOS

- src/fFileOpDlg.pas
- src/ffileproperties.pas
- src/filesources/filesystem/ufilesystemutil.pas
- src/filesources/gio/ugiofilesourceutil.pas
- src/filesources/wcxarchive/uwcxarchivecopyinoperation.pas
- src/filesources/wfxplugin/uwfxpluginutil.pas
- src/fsyncdirsdlg.pas
- src/udcutils.pas
- src/umaincommands.pas
Now DC uses options for file size when file replacing and also format number of files according to regional settings of OS. Tested only on Windows
> UPD: Format file sizes and counts in file dialogs (v.2)

- src/fattributesedit.lfm
- src/foptions.lfm
- src/foptions.pas
- src/frames/foptionsdirectoryhotlist.lfm
- src/frames/foptionsdirectoryhotlist.pas
- src/frames/foptionsfilesviewscomplement.lfm
- src/frames/foptionsfilesviewscomplement.pas
- src/frames/foptionsquicksearchfilter.lfm
- src/frames/foptionstabs.lfm
- src/frames/foptionstabsextra.lfm
- src/frames/foptionsterminal.lfm
- src/frames/foptionstoolbar.lfm
- src/frames/foptionstoolbarextra.lfm
- src/frames/foptionstoolbarmiddle.lfm
- src/frames/foptionstools.lfm
- src/frames/foptionstoolsdiffer.lfm
- src/frames/foptionstoolseditor.lfm
- src/frames/foptionstooltips.lfm
- src/frames/foptionstreeviewmenu.lfm
- src/frames/foptionstreeviewmenucolor.lfm
1. Added HelpKeywords for remaining pages.
2. Added Help button to show that you open Help. Button will be invisible when no HelpKeyword.
3. Some small changes: Default and Cancel for TAttributesEdit and change owner for calling from Option page (because when Position=poOwnerFormCenter the owner have to be properly set to avoid showing not at the center as it was before).
4. Remove now duplicate button in Hotlistdir.
Should I commit .po files? It's very difficult to compare. If should than as is or by merging only new important changes?
> ADD: Button Help for Options

- src/platform/udrivewatcher.pas
- src/platform/unix/linux/uudev.pas
- src/udriveslist.pas
Correct total size for mounted network devices and non mounted [optical] drives.
P.S. Changes in uudev.pas is not necessary but I think it'll bring to error in the future.
May be there is better possibility to fix unmounted optical drive size but I think Linux returns not correct disk size.
> FIX: Drive list popup for Linux

- src/doublecmd.lpr
- src/platform/unix/darwin/ucocoawidgetsetfix.pas
FIX #832: MultiRename: FileName & Extension fields not updated on MacOS.
such as `GetSelStart()` is missing in TCocoaWSCustomComboBox.
> FIX #832: MultiRename: FileName & Extension fields not updated on MacOS

- src/ftreeviewmenu.lfm
When opening a tree view menu (e.g. Directory Hotlist), automatic shortcuts are not applied to the short text of the item name. This update fixes this behavior.
Before:
After:
> UPD: Auto shortcuts in the tree view

- src/platform/ufilesystemwatcher.pas
- src/platform/unix/darwin/udarwinfswatch.pas
FIX: AutoRefresh: update directory correctly in FlatView mode on MacOS.
1.  in FlatView mode, AutoRefresh works incorrectly when the subdirectory added or renamed (on all OS)
2. the PR fix the issue on MacOS. when the subdirectory changed, Reload() the WatchPath
> FIX: AutoRefresh: update directory correctly in FlatView mode on MacOS

- src/platform/unix/darwin/ucocoawidgetsetfix.pas
FIX: COCOA: AutoComplete issue in IME input state in TCocoaWSCustomComboBoxEx.
disable AutoComplete until Cocoa IME Patch merged.
https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/40008
> FIX: COCOA: AutoComplete issue in IME input state in TCocoaWSCustomComboBoxEx

- src/fmain.pas
fix the notebook issue during startup on MacOS:
1. TCustomTabControl.GetControlClassDefaultSize() return 200 for Default Width
2. on Cocoa, it is likely to cause TCocoaTabControl not wide enough to accommodate all tabs loaded in LoadTabsXml() during startup.
3. when setting PageIndex in LoadTabsXml(), it will cause an extra tab switch.
4. and it will cause an extra directory to be monitored in FileView.
5. the issue can be effectively avoided by setting a larger width.
> FIX: COCOA: notebook issue during startup

- src/fileviews/ufileview.pas
- src/ufile.pas
- src/ufileproperty.pas
UPD: AutoRefresh: smarter visual blinking in TFileView.UpdateFile.
there are two cases in TFileView.UpdateFile()
1. file modified: VisualizeFileUpdate() should be called
eg. fpModificationTime, fpSize, fpAttributes, fpOwner changed
2. no modified: need not Visual Blink
only fpLastAccessTime or fpChangeTime changed
in this PR, reduce unnecessary blinking by distinguishing between two cases.
tested on Windows 11, MacOS 12 and Linux.
> UPD: AutoRefresh: smarter visual blinking in TFileView.UpdateFile

- src/ffileproperties.lfm
- src/ffileproperties.pas
FIX: file icon issue in FileProperties Form.
1. display file icon correctly
2. on Retina screen, display larger sized file icon (up to 48x48)
tested on MacOS 12 and Linux.
> FIX: file icon issue in FileProperties Form

- components/KASToolBar/kaspathedit.pas
after the Key `Return` handled in TKASPathEdit.handleSpecialKeys(), `Key` should be eaten.
otherwise `Return` may be handled again by the `Default` Button of the Form (eg. Form `TfrmOptionsFilePanelsColors`,`TfrmOptionsCustomColumns`)
tested on Windows 11, MacOS 12 and Linux.
> FIX: Key Return handled in TKASPathEdit.handleSpecialKeys()

- src/fileviews/ufileviewwithmainctrl.pas
it's an issue related to #420.
also throws an exception when DoubleClick on the Grid in the Form `TfrmOptionsCustomColumns` on MacOS.
> FIX: Cocoa: Exception raised when DoubleClick in TfrmOptionsCustomColumns on MacOS

- src/ffileproperties.lfm
Form `FileProperties` would be incorrectly closed by Button `Skip this File`.
it' caused by the property `ModalResult` of the button, which was incorrectly set to mrIgnore before.
> FIX: FileProperties would be incorrectly closed by Button "Skip this File"

- components/KASToolBar/kaspathedit.pas
- src/foptions.lfm
- src/foptions.pas
fix key ESC/RETURN handled in KasPathEdit & Options Dialog:
1. after the Key ESC/RETURN handled in TKASPathEdit.handleSpecialKeys(), Key should be eaten (there is a bug in #876)
2. in fOptions, set `btnCancel.Cancel`=`true` , and remove `alOptionsActionList`, handle `ESCAPE` correctly on all platforms
3. tested on Windows 11, MacOS12 and Linux
> FIX: key ESC/RETURN handled in Options Dialog & KasPathEdit

- src/fileviews/ubrieffileview.pas
Fixes Ctrl+WheelUp behaviour in Brief View
> fix Ctrl+WheelUp bug when font size = MinValue

- src/platform/unix/darwin/umydarwin.pas
- src/platform/unix/umyunix.pas
- src/platform/unix/ushellcontextmenu.pas
use `NSWorkspace.sharedWorkspace.unmountAndEjectDeviceAtPath()` instead of `diskutil unmount`.
`diskutil unmount` has a high probability of not successfully unmounting.
> UPD: DARWIN: unmount driver

- components/doublecmd/dcosutils.pas
copy file with CreationTime on MacOS (intel CPU supported):
1. there is a bug in FPC with intel CPU on MacOS
2. on MacOS with x86_64, struct `Stat64` should be used instead of `Stat`, and `lstat64()` should be called instead of `lstat()`.
3. `TDarwinStat64` had beed added for the workaround
tested on MacOS and Linux.
> FIX & UPD: copy file with CreationTime on MacOS (intel CPU supported)

- src/platform/unix/ushellcontextmenu.pas
currently, it would jump to the Root directory after unmounting the driver.
It would be more appropriate to jump to the Home directory.
unix-like system affected only ( eg. linux and MacOS )
> UPD: jump to Home directory instead of Root directory after unmounting the driver

- src/fmain.pas
in LCLCOCOA, there is an issue about the order of `CM_ENTER` messages in `edtCommand`
since CM_ENTER is sent delayed, when we press a Key in the main form, `edtCommand.SelStart` set in `TypeInCommandLine()` is overwritten when CM_ENTER is processed. if `edtCommand.AutoSelect=True`, it will cause all  text selected.
there is the MR in LCL, but it has not been merged yet: https://gitlab.com/freepascal.org/lazarus/lazarus/-/merge_requests/116
> FIX #937: CommandLine text is incorrectly all selected on MacOS

- components/dcpcrypt/dcpcrypt2.pas
update the dcpcrypt2.pas code to v2.0.4.2
https://gitlab.com/freepascal.org/lazarus/ccr/-/issues/31934
> dcpcrypt2.pas : upstream hash fix for large files

- src/ffileproperties.pas
in #539, may refer to unfinished controls in FileProp Dialog  creating.
an exception cause by `edtOctal.Text:= EmptyStr;` in `TfrmFileProperties.cbChangeModeClick`.
according to the screenshot and stack trace log, `edtOctal` will be called  before `edtOctal` created.
```
>>> GetTextMethod := TMethod(@Self.GetTextBuf); <<<
0 GETTEXT(0x0000000000000000) at control.inc:3605
1 SETTEXT(0x0000000000000000, 0x0000000000000000) at control.inc:5138
>>> edtOctal.Text:= EmptyStr; <<<
2 CBCHANGEMODECLICK(0x000000011b04f8f0, 0x0000000106c79f50) at ffileproperties.pas:452
3 CLICK(0x0000000106c79f50) at control.inc:2968
4 CLICK(0x0000000106c79f50) at buttoncontrol.inc:56
>>> TCustomCheckBox.DoClickOnChange <<<
5 DOCLICKONCHANGE(0x0000000106c79f50) at customcheckbox.inc:286
6 SETSTATE(0x0000000106c79f50, …
```
> FIX #539: FileProp Dialog: may refer to unfinished controls in Form creating

- src/platform/unix/darwin/udarwinfswatch.pas
FIX #963: AutoRefresh: realpath issue on MacOS
> FIX #963: AutoRefresh: realpath issue on MacOS

- src/platform/unix/darwin/udarwinfswatch.pas
_watchPaths and _watchRealPaths have non atomic changes => better use full synchronisation,
but this changes mostly avoiding out of range in loop
> FIX #963: MacOS crash in fswatch

- components/doublecmd/dcbasictypes.pas
- components/doublecmd/dcdarwin.pas
- components/doublecmd/dcdatetimeutils.pas
- components/doublecmd/dcosutils.pas
- components/doublecmd/dcunix.pas
- src/filesources/filesystem/ufilesystemfilesource.pas
- src/filesources/filesystem/ufilesystemsetfilepropertyoperation.pas
- src/platform/ufindex.pas
- src/rpc/uadministrator.pas
- src/umaincommands.pas
1. FileTime includes ModificationTime, CreationTime, AccessTime, ChangeTime
2. when copying files in DC, the fractional parts of FileTime are ignored
3. in SetFileProperties Dialog, the milliseconds are ignored
1. because it involves modifications in many places, the principle of this PR is to make as few changes as possible, so the original function and the `Ex` function version are retained at the same time. after this PR is merged, it should take one or two more PRs to replace them all with the new `Ex` version.
2. record `TFileTimeEx` added, which corresponds to `TFileTime`, but adds support for nanosecond precision. not directly modifying `TFileTime` is the reason mentioned in 1st, to minimize the places that need to be modified.
3. the `Ex` series functions added:
`in DCBasicTypes` …
> ADD: FileTime: at least millisecond precision supported on Linux and MacOS

- src/platform/uicontheme.pas
FIX: memory leaks in TIconTheme.Create().
dynamic arrays used for anonymous parameters passed by value, cause memory leaks (maybe a bug of Free Pascal).
> FIX: memory leaks in TIconTheme.Create()

- src/platform/unix/darwin/umydarwin.pas
FIX: memory leaks in uMyDarwin.
although it is not a real memory leak, it can avoid the memory leak warning of heaptrc.
> FIX: memory leaks in uMyDarwin

- src/fileviews/ufileviewwithmainctrl.pas
the workaround for IME in fileview (F2 rename) can be removed.
> UPD: workaround for IME in fileview (F2) are removed by the update of Lazarus Lcl (issue 40008)

- src/platform/unix/darwin/udarwinfswatch.pas
In Cocoa, as a created and resident thread, NSAutoreleasePool needs to be added to release memory for the Autorelease variable, otherwise it will not be released until the thread ends.
> FIX: memory leaks in udarwinfswatch

- src/filesources/filesystem/ufilesystemfilesource.pas
- src/filesources/multilist/umultilistfilesource.pas
- src/filesources/ufilesource.pas
- src/filesources/wfxplugin/uwfxpluginfilesource.pas
FIX: memory leaks in IFileResource.RetrieveProperties().
dynamic arrays used for anonymous parameters passed by value, cause memory leaks (maybe a bug of Free Pascal).
> FIX: memory leaks in IFileResource.RetrieveProperties()

- src/uquickviewpanel.pas
when in QuickSearch or QuickFilter edit, QuickViewPanel(Control-Q) focused wrong active control.
it's cause by fixed `FFileView.SetFocus;`
now SetFocus to last active control.
> FIX: QuickViewPanel: focus wrong control when QuickSearch or QuickFilter

- components/doublecmd/dcstrutils.pas
- src/udcutils.pas
Fixes #130 
Sometimes when using source code from different sources, non-normalized paths can be a pain and currently double commander can't read those.
A perfect cross platform solution would be the logic in the function `path::lexically_normal()`  found in the following link:
https://github.com/gcc-mirror/gcc/blob/b24acae8f4d315a5b071ffc2574ce91c7a0800ca/libstdc%2B%2B-v3/src/c%2B%2B17/fs_path.cc#L1686
However, in the meantime I introduce this solution:
The WINAPI `GetFullPathName` function is superior to the current double commander implementation, it solves complex cases of non-normalized path forms such as `c:/windows\/system32///\..`
> Fix: directory change to non-normalized paths - issue #130

- src/doublecmd.lpr
This commit fixes crash during exit if doublecmd compiled with FPC 3.3.1.
This commit doesn't fix or break anything if doublecmd compiled with FPC 3.2.2.
doublecmd compiled with FPC 3.3.1 before this commit was broken like this:
1. unix unit (used by cthreads unit) allocates memory using built-in memory manager
2. cmem unit replaces built-in memory manager with cmem memory manager
3. user exits doublecmd
4. something tries to free memory allocated in step 1 with cmem memory manager
> FIX: Use cmem unit before cthreads unit (#1553)

- language/doublecmd.hu.po
- updated from the POT file
- fixed: some typos
- fixed: some missing shortcuts
- fixed: removed some unnecessary shortcuts
(in the past there were some other translators as well, so I just accepted their works, but will review in my free time....
I'm always translating as "vi (like in serbian language)" not "ti (like in serbian language)", but found a translation as "ti")
: and also will find a way to delete the unneeded branch(es)
thank you!
> update: hungarian translation

- src/udcutils.pas
also simplify IntToStrTS (smaller, less variables)<table><tr><th colspan="2">LC_ALL=C</th></tr><tr><th>before</th><th>after</th></tr><tr><td><img src="https://github.com/doublecmd/doublecmd/assets/91378413/610075bf-d0a3-463c-80b5-a81cd231598b"></td><td><img src="https://github.com/doublecmd/doublecmd/assets/91378413/14a61a70-86fc-4143-8831-60a90116e04b"></td></tr></table>
> FIX: IntToStrTS when ThousandSeparator is NUL

- src/filesources/multiarchive/umultiarchivedynamicparser.pas
- src/filesources/multiarchive/umultiarchiveparser.pas
- src/umultiarc.pas
workaround for zpaqfranz/fanext etc which show in the size position thousandth separators, -, -dir- and other fancy stuff that break the parser
> UPD: MultiArc - cleaning chars in size string w/o additional helpers

- src/feditor.lfm
- src/feditor.lrj
- src/feditor.pas
The implemented feature inserts current time and date into the current position of the edited text, like it Notepad in Windows does.
> ADD: Built-in editor menu item "Edit - Time/Date".

- src/platform/uOSUtils.pas
Fix https://github.com/doublecmd/doublecmd/issues/1966
> Fix Shift+Enter when path has space

- language/doublecmd.zh_CN.po
I found some wrong translation:
**婪**删除  -> should be **要**删除 
"个文件" -> should be “文件”
screenshot:
Could you help to check it? Thanks!
> FIX: LANG: zh_CN: Fix translations
